blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/vynazevedo/sonarqube-selfhosted/discussions
    about: Ask questions and discuss ideas in Discussions
